---
x-service-common: &service-common
  restart: always

services:
  web:
    <<: *service-common
    container_name: web.${COMPOSE_PROJECT_NAME-colouring-dresden}
    image: docker.io/library/nginx:${NGINX_VERSION-1.25}
    volumes:
      #######################################################
      - nginx-cert:/etc/nginx/ssl
      - nginx-conf:/etc/nginx/conf.d
      # # generate new cert
      - ./data/web/00-https.sh:/docker-entrypoint.d/00-https.sh:Z
      # # otherwise provide own cert
      # - ./data/web/ssl/cert.pem:/etc/nginx/ssl/cert.pem:Z
      # - ./data/web/ssl/key.pem:/etc/nginx/ssl/key.pem:Z
      #######################################################
      - ./data/web/nginx.conf.template:/etc/nginx/templates/default.conf.template:Z
    environment:
      - DOMAIN=${COMPOSE_PROJECT_NAME-colouring-dresden}
      - WEB_DOMAIN=web.${COMPOSE_PROJECT_NAME-colouring-dresden}
      - PROXY_API_DEST=http://app.${COMPOSE_PROJECT_NAME-colouring-dresden}:${APP_PORT-3000}
      - PUB_HTTPS_PORT=${PUB_HTTPS_PORT-8443}
    security_opt:
      - label=type:container_t
    depends_on:
      app:
        condition: service_started
    ports:
      - ${PUB_HTTP_PORT-8080}:80
      - ${PUB_HTTPS_PORT-8443}:443
      - 3000:3000
      - 3001:3001

  app:
    <<: *service-common
    container_name: app.${COMPOSE_PROJECT_NAME-colouring-dresden}
    image: ${APP_CONTAINER_IMAGE-localhost/colouring-dresden}:${NODE_IMAGE_VERSION-20-slim}
    build:
      context: .
      additional_contexts:
        app: ../app
      dockerfile: Containerfile
      target: colouring-dresden
      no_cache: true
      args:
        - NODE_IMAGE_VERSION=${NODE_IMAGE_VERSION-20-slim}
    environment:
      - PGDATABASE=${POSTGRES_DBNAME-colouringdresdendb}
      - PGUSER=${POSTGRES_USER-colouringdresdendb_user}
      - PGPASSWORD=${POSTGRES_PASS-colouringdresdendb_user_pw}
      - PGHOST=db.${COMPOSE_PROJECT_NAME-colouring-dresden}
      - PGPORT=5432
      - APP_COOKIE_SECRET=${APP_COOKIE_SECRET-123456}
      - HOST=app.${COMPOSE_PROJECT_NAME-colouring-dresden}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ../app/razzle.config.js:/app/razzle.config.js:Z
    #ports:
    #  - 3000:3000
    #  - 3001:3001
    # command: ["npm", "run", "start"]

  db:
    <<: *service-common
    container_name: db.${COMPOSE_PROJECT_NAME-colouring-dresden}
    image: docker.io/kartoza/postgis:${POSTGRES_MAJOR-13}
    environment:
      - POSTGRES_DBNAME=${POSTGRES_DBNAME-colouringdresdendb}
      - POSTGRES_USER=${POSTGRES_USER-colouringdresdendb_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD-colouringdresdendb_user_pw}
      - POSTGRES_HOST_AUTH_METHOD=${POSTGRES_HOST_AUTH_METHOD-scram-sha-256}
      - POSTGRES_MULTIPLE_EXTENSIONS=${POSTGRES_MULTIPLE_EXTENSIONS-hstore,postgis,pgcrypto,pg_trgm}
      - PGDATA=/var/lib/postgresql/${POSTGRES_MAJOR-13}/main
      - DB_PORT=5432
      - DB_HOST=db.${COMPOSE_PROJECT_NAME-colouring-dresden}
    volumes:
      - ./data/db/00-migrations.sh:/docker-entrypoint-initdb.d/00-migrations.sh:Z
      - ${MIGRATIONS_DIR_SRC-../migrations}/:/docker-entrypoint-initdb.d/migrations/:Z
      - db-data:/var/lib/postgresql/${POSTGRES_MAJOR-13}/main
    healthcheck:
      test: ["CMD", "su", "-", "postgres", "-c", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    security_opt:
      - label=type:container_t

volumes:
  nginx-cert:
  nginx-conf:
  db-data: