ARG NODE_IMAGE_VERSION="20-slim"
ARG APP_DIR="/app"

###############################################################################
FROM node:${NODE_IMAGE_VERSION} AS builder
###############################################################################
RUN apt-get -y update && apt-get -y upgrade

ARG APP_DIR
RUN mkdir -p ${APP_DIR} 
WORKDIR ${APP_DIR}
RUN chown node:node .
COPY --chown=node:node --from=app . .
USER node

#ARG NODE_OPTIONS="--max-old-space-size=4096"
# from node v17+ [node v17, OpenSSL 3.0](https://nodejs.org/en/blog/release/v17.0.0)
ARG NODE_OPTIONS="--max-old-space-size=4096 --openssl-legacy-provider"
RUN npm cache clean --force
RUN npm install --verbose
RUN npm install cors --save-dev --legacy-peer-deps
RUN npm run build -- --noninteractive
###############################################################################


###############################################################################
FROM node:${NODE_IMAGE_VERSION} AS colouring-cities
###############################################################################
RUN apt-get -y update && apt-get -y upgrade \
    && apt-get -y clean \
    && apt-get -y autoclean \
    && apt-get -y autoremove \
    && rm -rf /var/cache/apt/archives/*.deb \
    && rm -rf /var/lib/apt/lists/*

ARG APP_DIR
RUN mkdir -p ${APP_DIR} 
WORKDIR ${APP_DIR}
RUN chown node:node .
COPY --chown=node:node --from=builder ${APP_DIR} .
USER node

ENV PGDATABASE=colouring-cities
ENV PGUSER=colouring-cities-user
ENV PGPASSWORD=
ENV PGHOST=localhost
ENV PGPORT=5432
ENV APP_COOKIE_SECRET=colouring-cities

# ENV NODE_OPTIONS="--max-old-space-size=4096" # before node v18
ENV NODE_OPTIONS="--max-old-space-size=4096 --openssl-legacy-provider"

CMD ["npm", "run", "start:prod"]
#CMD ["npm", "run", "start"]
###############################################################################
